apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: load-hotrod
  name: load-hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: load-hotrod
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: load-hotrod
    spec:
      containers:
        - env:
            - name: ATTACKED_HOST
              value: http://hotrod.signoz.svc.cluster.local:9000
            - name: LOCUST_MODE
              value: standalone
            - name: LOCUST_OPTS
              value: --headless -u 10 -r 1
            - name: NO_PROXY
              value: standalone
            - name: QUIET_MODE
              value: "false"
            - name: TASK_DELAY_FROM
              value: "5"
            - name: TASK_DELAY_TO
              value: "30"
          image: grubykarol/locust:1.2.3-python3.9-alpine3.12
          name: load-hotrod
          ports:
            - containerPort: 8089
          resources: {}
          volumeMounts:
            - mountPath: /locust
              name: load-hotrod-cm0
      hostname: load-hotrod
      restartPolicy: Always
      volumes:
        - configMap:
            name: load-hotrod-cm0
          name: load-hotrod-cm0
status: {}
