kind: Service
apiVersion: v1
metadata:
  name: jaeger-external-service
  namespace: ingress
spec:
  type: ExternalName
  externalName: tobs-jaeger-promscale.default.svc.cluster.local
  ports:
  - port: 16686
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-jaeger
  namespace: ingress
spec:
  rules:
  - host: jaeger.promscale.lo
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jaeger-external-service
              port: 
                number: 16686
